### ISSUE TITLE
Usage example for Typescript - getting an error

### ISSUE THREAD

**Issue by checklist** [ammarahm-ed/react-native-actions-sheet#106]
Hello,

I posted this issue on SO regarding the usage with Typescript. Can you please assist?

https://stackoverflow.com/questions/68757797/typescript-createref-for-actionsheet-react-native

```tsx
export default function MyFunc(){
   const actionSheetRef = createRef<ActionSheet>()
   useEffect(() => {
        actionSheetRef.current?.setModalVisible(props.open)
   }, [props.open])
   return (
        <>
            <ActionSheet
                ref={actionSheetRef}
                onClose={props.onClose}
            >
            // more code here  ....
        <>)
}
```

I also added a tag for your project so others can find it easier.

Thanks for the great library!

**Comment by ammarahm-ed** [comment]
> Hello,
> 
> I posted this issue on SO regarding the usage with Typescript. Can you please assist?
> 
> https://stackoverflow.com/questions/68757797/typescript-createref-for-actionsheet-react-native
> 
> export default function MyFunc(){
>    const actionSheetRef = createRef<ActionSheet>()
>    useEffect(() => {
>         actionSheetRef.current?.setModalVisible(props.open)
>    }, [props.open])
>    return (
>         <>
>             <ActionSheet
>                 ref={actionSheetRef}
>                 onClose={props.onClose}
>             >
>             // more code here  ....
>         <>)
> }
> 
> I also added a tag for your project so others can find it easier.
> 
> Thanks for the great library!

What issue are you facing?

**Comment by checklist** [comment]
![image](https://user-images.githubusercontent.com/1918168/129210179-4452a9bd-f011-42ea-8801-4833da5e69a0.png)


Type 'RefObject<ActionSheet>' is not assignable to type '(string & MutableRefObject<{ setModalVisible(visible?: boolean | undefined): void; show(): void; hide(): void; handleChildScrollEnd(): void; snapToOffset(offset: number): void; }>) | (RefObject<...> & MutableRefObject<...>) | (((instance: ActionSheet | null) => void) & MutableRefObject<...>) | undefined'.
  Type 'RefObject<ActionSheet>' is not assignable to type '((instance: ActionSheet | null) => void) & MutableRefObject<{ setModalVisible(visible?: boolean | undefined): void; show(): void; hide(): void; handleChildScrollEnd(): void; snapToOffset(offset: number): void; }>'.
    Type 'RefObject<ActionSheet>' is not assignable to type '(instance: ActionSheet | null) => void'.
      Type 'RefObject<ActionSheet>' provides no match for the signature '(instance: ActionSheet | null): void'.

**Comment by checklist** [comment]
![image](https://user-images.githubusercontent.com/1918168/129210290-9a0af3ac-bd31-46fb-87ab-e4e36d1e006e.png)

**Comment by ammarahm-ed** [comment]
> ![image](https://user-images.githubusercontent.com/1918168/129210290-9a0af3ac-bd31-46fb-87ab-e4e36d1e006e.png)
> 

You should use `useRef` not `createRef`

**Comment by checklist** [comment]
const actionSheetRef = useRef<ActionSheet>()

This gives an error as well: 

Type 'RefObject<ActionSheet>' is not assignable to type '(string & MutableRefObject<{ setModalVisible(visible?: boolean | undefined): void; show(): void; hide(): void; handleChildScrollEnd(): void; snapToOffset(offset: number): void; }>) | (RefObject<...> & MutableRefObject<...>) | (((instance: ActionSheet | null) => void) & MutableRefObject<...>) | undefined'.
  Type 'RefObject<ActionSheet>' is not assignable to type '((instance: ActionSheet | null) => void) & MutableRefObject<{ setModalVisible(visible?: boolean | undefined): void; show(): void; hide(): void; handleChildScrollEnd(): void; snapToOffset(offset: number): void; }>'.
    Type 'RefObject<ActionSheet>' is not assignable to type '(instance: ActionSheet | null) => void'.
      Type 'RefObject<ActionSheet>' provides no match for the signature '(instance: ActionSheet | null): void'.

**Comment by hannanhafeez** [comment]
@checklist a temporary solution is to do it like this:

```
type SheetRef = {
	setModalVisible(visible?: boolean | undefined): void;
	show(): void;
	hide(): void;
	handleChildScrollEnd(): void;
	snapToOffset(offset: number): void;
}

type refType = (React.LegacyRef<ActionSheet> & React.MutableRefObject<SheetRef>) | undefined
```

and then typecast the ref like: 
```
const actionSheetRef = useRef<SheetRef>();

<ActionSheet ref={actionSheetRef as refType}>
```
It removed the squiggly lines for me at least and I also got type-definition on `actionSheetRef` back.

**Comment by checklist** [comment]
> @checklist a temporary solution is to do it like this:
> 
> ```
> type SheetRef = {
> 	setModalVisible(visible?: boolean | undefined): void;
> 	show(): void;
> 	hide(): void;
> 	handleChildScrollEnd(): void;
> 	snapToOffset(offset: number): void;
> }
> 
> type refType = (React.LegacyRef<ActionSheet> & React.MutableRefObject<SheetRef>) | undefined
> ```
> 
> and then typecast the ref like:
> 
> ```
> const actionSheetRef = useRef<SheetRef>();
> 
> <ActionSheet ref={actionSheetRef as refType}>
> ```
> 
> It removed the squiggly lines for me at least and I also got type-definition on `actionSheetRef` back.

This seems to have taken the issue away and no errors now. But, I still think there is something wrong with the Typescript definitions in the library and the ActionSheet is not defined properly. 

BTW - I am using TS 4.3.5

**Comment by ammarahm-ed** [comment]
Fixed in `v0.5.3`. Use `ActionSheetRefObject` type.

**Comment by efstathiosntonas** [comment]
@ammarahm-ed still getting the `Type 'RefObject' is not assignable to type '(string & MutableRefObject<{ setModalVisible(visible?: boolean | undefined): void; bla bla` after upgrading to `0.5.3`, not that it matters but I'm using typescript `4.4.2`

**Comment by ammarahm-ed** [comment]
> const actionSheetRef = createRef<ActionSheet>()
> <ActionSheet
>             ref={actionSheetRef}
> ...
> />
> 
> The above works for me with v0.54.
> 
> Thanks.

Use as it is used in the example. Don't use `createRef` in functional components. Use `useRef<ActionSheet>()`.

**Comment by checklist** [comment]
But that brings me back to the same initial issue:
```
const actionSheetRef = useRef<ActionSheet>()
 <ActionSheet
            ref={actionSheetRef}
            onClose={props.handleClose}
        >
```

This always brings the error on the ref={actionSheetRef} and the problem is not solved :-(

**Comment by ammarahm-ed** [comment]
@johnbonds 

```tsx
const actionSheetRef = React.useRef<ActionSheet>(null)
```
should work.
