### ISSUE TITLE
Padding bottom is overwritten by the libraries style

### ISSUE THREAD

**Issue by naderalfakesh** [ammarahm-ed/react-native-actions-sheet#138]
``` 
<ActionSheetBase
  containerStyle={{
    ...styles.container,
    paddingBottom: insets.bottom,
    ...containerStyle,
    }}>
  {children}
</ActionSheetBase>
```
We are setting bottom padding with the value coming from safe area context on, I was able to solve this by wrapping content with a view and passing the padding to it. 
But I have one sheet that has a sticky button so it should be without bottom spacing but I cannot overwrite the padding.

Thanks for the great efforts, keep it up.

**Comment by theneekz** [comment]
Same problem, can't affect paddingBottom in containerStyle

**Comment by ammarahm-ed** [comment]
@theneekz Its not possible with the current mechanism of how the sheet works. Paddings are locked to a specific number. You can add padding to an inner view or render a <View/> at bottom of your sheet and give it an height.

**Comment by theneekz** [comment]
That's what I've come to realize...thanks for clarifying. I would like to have the ActionSheet rise up from a different height ideally, which I also don't think is possible. This was one route I tried to get around that with a few other styling changes but I don't think it's possible to create the effect.

**Comment by theneekz** [comment]
As close as I can get it right now: 
```
<ActionSheet
    containerStyle={{
        backgroundColor: 'transparent',
    }}
    indicatorStyle={{ backgroundColor: 'grey', top: 20, zIndex: 10 }} 
    ...
        <View 
            style={{ 
               marginBottom: tabBarHeight,
               paddingHorizontal: '5%',
               backgroundColor: 'white',
               borderTopWidth: 20,
               borderTopLeftRadius: 10,
               borderTopRightRadius: 10,
               borderTopColor: 'white',
            }}>
           ....
````
![Screen Shot 2022-02-03 at 11 11 40 AM](https://user-images.githubusercontent.com/56894041/152393278-a72a50dd-d415-4bb6-be25-7ef570bcd305.png)

**Comment by ammarahm-ed** [comment]
@theneekz I can see what you are trying to do here. The Sheet opens up in a Modal. So if the user cannot interact with the buttons in bottom tab, I think it will end up being a confusing UX. One way around that would be to render the tab at the same position inside the sheet. So when the Sheet opens up, the bottom tabs are in there and user can tap on them to close the sheet and navigate to the respective tab.

What you are trying to achieve here is possible with a Sheet that does not open in a Modal but in a View container.

**Comment by theneekz** [comment]
Thanks, that makes sense. I think rerendering the bottom tabs inside the modal is the only solution for using this library. There's no way to render this inside a View container right rather than a modal right?

**Comment by ammarahm-ed** [comment]
@theneekz Right not it won't be possible to do it.

**Comment by johnny-mcfadden-dailypay** [comment]
@[mydesweb](https://github.com/mydesweb) also facing the same issue. Did you manage to find a fix? 
Perhaps @ammarahm-ed  can save the day 🙏 🙏 

<img width="449" alt="Screenshot 2022-06-01 at 12 01 14" src="https://user-images.githubusercontent.com/93137292/171389701-92e1f4da-75a2-4269-a761-794555c98083.png">

**Comment by HyopeR** [comment]
I have the same problem on Ios and Android platforms. I am sharing 2 screenshots and code blocks to elaborate on the subject.

**Code:**
```
<ActionSheet containerStyle={{backgroundColor: 'red'}}>
      <View style={{ width: '100%', height: 200, backgroundColor: 'green'}} />
<ActionSheet>
```

**Screenshots:**
<table role="table">
<thead>
<tr>
<th>Android</th>
<th>Ios</th>
</tr>
</thead>
<tbody>
<tr>
<td><a target="_blank" href="https://user-images.githubusercontent.com/36919703/185758513-33f4d6ba-4aa3-4b22-8730-733529888f99.png"><img src="https://user-images.githubusercontent.com/36919703/185758513-33f4d6ba-4aa3-4b22-8730-733529888f99.png" alt="image" height="400"></a></td>
<td><a target="_blank" href="https://user-images.githubusercontent.com/36919703/185758519-46304bcb-026f-4045-85f7-e153b7a401fe.png"><img src="https://user-images.githubusercontent.com/36919703/185758519-46304bcb-026f-4045-85f7-e153b7a401fe.png" alt="image" height="400"></a></td>
</tr>
</tbody>
</table>

**Comment by HyopeR** [comment]
I think I found the problem. There is a problem with the following part of the source code. 
At: [https://github.com/ammarahm-ed/react-native-actions-sheet/blob/master/src/index.tsx](https://github.com/ammarahm-ed/react-native-actions-sheet/blob/master/src/index.tsx)

```

{overdrawEnabled ? (
    <Animated.View
        style={{
            height: overdrawSize,
            position: "absolute",
            bottom: -overdrawSize
            backgroundColor: props.containerStyle?.backgroundColor || "white",
            width: dimensions.width,
        }}
    />
) : null}
```

This is what this part looks like when it comes out of the package.
**Look at the bottom value.**
```
<View style={{
        height: 200,
        backgroundColor: (containerStyle === null || containerStyle === void 0 ? void 0 : containerStyle.backgroundColor) || "#ffffff",
        position: "absolute",
        bottom: -195, // 5 pixels missing here. 
        width: (containerStyle === null || containerStyle === void 0 ? void 0 : containerStyle.width) || "100%"
    }}
/>
```

There is a problem in the part where the 'overdrawSize' value is given as negative. 
And the difference of 5 pixels creates the padding.

**Comment by ammarahm-ed** [comment]
@HyopeR The master branch has the unreleased version of the library. You must be using the older version. A new version will be out soon which fixes this. I will investigate this and see if this padding at bottom could be avoided completely.

**Comment by ammarahm-ed** [comment]
You can try installing the `vnext` branch but beware it has many breaking changes so its best to wait until i release v0.8.0

**Comment by ammarahm-ed** [comment]
This is fixed in v0.8.0. Will release today.

**Comment by alwazqazi** [comment]
Still facing this issue on v0.8.0. please help.

the pink area is containerStyle
![actionsheetSucks](https://user-images.githubusercontent.com/105052798/228221088-fffeaabb-8056-4835-8314-9a0c55aaaac4.jpeg)




![actionsheetultrasucks](https://user-images.githubusercontent.com/105052798/228221750-3b9d2562-a058-4369-a530-fbf9c73e7973.jpeg)

**Comment by MoRa2297** [comment]
> Still facing this issue on v0.8.0. please help.
> 
> the pink area is containerStyle ![actionsheetSucks](https://user-images.githubusercontent.com/105052798/228221088-fffeaabb-8056-4835-8314-9a0c55aaaac4.jpeg)
> 
> ![actionsheetultrasucks](https://user-images.githubusercontent.com/105052798/228221750-3b9d2562-a058-4369-a530-fbf9c73e7973.jpeg)

The same for me!
Pls help!

**Comment by adrian3ka** [comment]
<img width="348" alt="Screenshot 2023-06-29 at 09 34 19" src="https://github.com/ammarahm-ed/react-native-actions-sheet/assets/31057437/942834ba-c128-4cb7-bfb0-2286fbeb05c0">
Still happening to me, there's an excess white background in the image. I'm using version `0.8.29`.

Thanks.

**Comment by andrisole92** [comment]
Happening to me as well

**Comment by nickpagee** [comment]
anyone found fix for this? just lost days trying to fix this

**Comment by Vayts** [comment]
@nickpagee
Did you find any solution?
