### ISSUE TITLE
Horizontal layout support

### ISSUE THREAD

**Issue by vinters768** [ammarahm-ed/react-native-actions-sheet#15]
Hi! Thanks for this awesome plugin. Portrait mode is working as expected, but horizontal layout does not trigger the content view, the background in toggled as I can see it turning darker.

Could you please look in to it? 

Thanks

**Comment by ammarahm-ed** [comment]
Lately I have only tested it on a tablet and a portrait mode on mobile. I will look into it today and try to fix landscape mode ASAP! Thank you for pointing it out. I think that the heights etc need to be recalculated when device orientation changes. The problem occurs because the actionsheet still thinks the device is in portrait. Thats why it does not show up, it hides behind as landscape is half as tall as portrait mode.

**Comment by ammarahm-ed** [comment]
So I have attempted to fix the horizontal layout issue and I think it has been fixed. I am publishing a new version on npm. Try it out and report back if you face any issue.

**Comment by vinters768** [comment]
@ammarahm-ed  thanks for the quick update.. I can see that it's still not working quite well. Please see screenshots:
![Simulator Screen Shot - iPhone 8 Plus - 2020-03-21 at 17 24 02](https://user-images.githubusercontent.com/13395036/77229839-cc006380-6b98-11ea-8c19-9f14cf4f8e21.png)
![Simulator Screen Shot - iPhone 8 Plus - 2020-03-21 at 17 24 11](https://user-images.githubusercontent.com/13395036/77229842-cf93ea80-6b98-11ea-9dcd-bd683bfcd0a0.png)
code:
`<ActionSheet
        headerAlwaysVisible={true}
        containerStyle={{
          backgroundColor: Colors.MAIN_DARK,
        }}
        ref={ref => (this.actionSheet = ref)}
      >
        <View>
          <FlatList
            data={defaultItem ? [defaultItem, ...data] : data}
            keyExtractor={(item, index) => `item_${index}_key_${item.id}`}
            renderItem={({ item, index }) => (
              <TouchableOpacity
                onPress={() => {
                  this.actionSheet.setModalVisible();
                  onItemPicked(item.id);
                }}
              >
                <View
                  style={{
                    ...Styles.default.center,
                    backgroundColor:
                      selectedId && item.id == selectedId
                        ? Colors.LIST_ACTIVE
                        : 'transparent',
                    marginBottom: Mixins.moderateScale(5),
                  }}
                >
                  <Text
                    style={{
                      padding: Spacing.SCALE_8,
                      color: Colors.WHITE,
                      fontSize: Mixins.moderateScale(14),
                    }}
                  >
                    {item.name}
                  </Text>
                </View>
              </TouchableOpacity>
            )}
          />
        </View>
      </ActionSheet>`

**Comment by ammarahm-ed** [comment]
Are you sure you are using the latest version? Remove node_modules folder and in your package.json file, update the version of react-native-actions-sheet to 0.2.2 or run yarn add react-native-actions-sheet@0.2.2

**Comment by ammarahm-ed** [comment]
Check the example, horizontal mode is working in the example

**Comment by vinters768** [comment]
@ammarahm-ed just ran: 
`npm view react-native-actions-sheet version
0.2.2`

**Comment by ammarahm-ed** [comment]
I think it is working on android, but on iOS it is not working. I am looking into the issue right now.

**Comment by vinters768** [comment]
@ammarahm-ed could you please try the data set I am using? With the same construction of ActionSheet component?

**Comment by ammarahm-ed** [comment]
@vinters768 can you test on android?

**Comment by vinters768** [comment]
@ammarahm-ed sure, give me a few minutes

**Comment by vinters768** [comment]
@ammarahm-ed yes, android looking good, but the problem still persists on iOS

**Comment by ammarahm-ed** [comment]
@vinters768 same here, I am trying to fix it right now on iOS. Hope it get fixed soon.

**Comment by ammarahm-ed** [comment]
Hey I have made an attempt to fix the problem on iOS. can you test using the master branch? 

go to your package.json file and replace 

```jsx
 "react-native-actions-sheet": "^0.2.2"
```
with 
```jsx
 "react-native-actions-sheet": "https://github.com/ammarahm-ed/react-native-actions-sheet.git"
```
and then run:
`yarn add https://github.com/ammarahm-ed/react-native-actions-sheet.git` 

then run it on iOS and see if its working now. for me its working.

**Comment by ammarahm-ed** [comment]
![Screen Shot 1399-01-02 at 11 45 31 PM](https://user-images.githubusercontent.com/40239442/77234159-1b14bb80-6bce-11ea-80c9-1c245eb9f437.png)

**Comment by vinters768** [comment]
@ammarahm-ed did what you said, no difference, are you sure you pushed it to remote?

**Comment by ammarahm-ed** [comment]
@vinters768 I have pushed the code to master branch, it is working here for me in the simulator. Can you go into node_modules/react-native-actions-sheet/src/index.js file and check if the ´_showModal´ function has setTimeout() of 100md inside? If its there, try to increase the timeout value from 100 to 200 or more..  See if it works in landscape mode for you then. 

Its late here at night, if it does not work still, i will fix it in the morning probably.

**Comment by vinters768** [comment]
@ammarahm-ed changed it  to 200-500 no change. I played around with line: 336, it seems to be responsible for the height.

**Comment by ammarahm-ed** [comment]
```jsx
setTimeout(() => {
        this.scrollViewRef.current.scrollTo({
          x: 0,
          y: scrollOffset,
          animated: false
        });

 setTimeout(() => {
if (animated) {
          this.transformValue.setValue(scrollOffset);
          Animated.spring(this.transformValue, {
            toValue: 0,
            bounciness: bounceOnOpen ? bounciness : 1,
            speed: openAnimationSpeed,
            useNativeDriver: true
          }).start()}},50)
        


        }
      }, 100);


```
Also set this.isRecoiling to false in the constructor. 

Basically I have wrapped the animation into another timeout function. Try it out.

**Comment by vinters768** [comment]
@ammarahm-ed this seems to fix it, thanks 👍 but first open is jittering, looks like  it sets height to high and then drops it to correct one. Do you have the same?

**Comment by ammarahm-ed** [comment]
Try to set outer timeout to 50ms and inner timeout to 10 or 20ms and I hope it will go away. This is kind of a hack but i think it will reduce the gitter.  Reduce the timeout even lower until you see no gitter anymore and the actionSheet is working.

**Comment by vinters768** [comment]
@ammarahm-ed will try that.. Will you work on a more permanent solution? Thanks 👍

**Comment by ammarahm-ed** [comment]
Yes I will probably but this seems to work for now. Also I would suggest that If your FlatList is not very long,try not to use it and instead use simple ScrollView and map the values to components. Because the ActionSheet wraps everything in a ScrollView so there is no virtualization and if you have a small list. Its okay if there is none.

**Comment by ammarahm-ed** [comment]
I need to investigate more why it is occuring, but the actual issue is still unclear, maybe after layout it takes a while for the list to load the data when in horizontal mode so it does not Scroll at start when no timeout is used.

**Comment by ammarahm-ed** [comment]
This has been fixed now in the new release. I am closing this issue. Open it if you face the problem.

**Comment by kaandurat** [comment]
Seems like this issue still exists on iOS. Android works fine. I solved it with [this commit](https://github.com/kaandurat/react-native-actions-sheet/commit/1c7dc4667e11edc5933fd20f08d36fa741e4bb33)

**Comment by ammarahm-ed** [comment]
I don't understand how changing the timeout value helps in fixing the issue? Can you shed some light?

**Comment by kaandurat** [comment]
@ammarahm-ed from what I've seen  safeAreaPaddingTop.current stays undefined which prevents the library from working properly. Do you have the same issue?

**Comment by ammarahm-ed** [comment]
@kaandurat that was fixed in v0.8.10. check that.

**Comment by benkaiser** [comment]
@ammarahm-ed I think this may be related to this issue, when switching between horizontal and vertical layouts I am seeing the actionsheet being placed too high on portrait and too low on landscape (almost as if when transitioning it is using the height of the previous orientation for calculating the translateY position).

It works when it first opens in either orientation, but goes wrong when I change orientation while the action sheet is visible.

**Comment by benkaiser** [comment]
@ammarahm-ed looks like the issue in my case is a stale value of `dimensions.height` inside `onSheetLayout`.
It seems to be fixed by re-fetching the value. I'll create a PR.

**Comment by benkaiser** [comment]
Fix PR for the above: #259
